name: GitHub Universe Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    paths:
      - "."
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v3.0.3
